 <script>
	$(document).ready(function(){
		 $("#btn_ajouter").on('click',function(){
				//alert("aaaa")
				var num_cli = $("#id_cli").val();
				var nom_cli = $("#nom_cli").val();
				var dt_num = $("#dt_num").val();
				
				if(num_cli == "" || nom_cli == "" || dt_num == ""){
					alert('vous dévez completer le champ vide')
				}else{
					if(confirm("Voulez vous vraiment Ajouter")){
						$.ajax({
							type:"POST",
							url:"monappli/add",
							data:{
								n_cli:num_cli,
								nom_cli:nom_cli,
								dt_num:dt_num
							},
							success:function(){
								alert('insertion effectué');
								$("#annul_ajout").trigger("click");
								location.reload();
							}
						})
					}
				}
		   });
		   
		   $("#dt_num").datepicker({
				dateFormat:"dd-mm-yy"
		   });
	})
 </script>
 <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ajouter un nouveau client</h4>
      </div>
      <div class="modal-body" id="ajout_cl">
			<table class="table table-striped">
				<tr>
					<td>Identifiant du client</td>
					<td><input type="text" class="form-control" id="id_cli"></td>
				</tr>
				
				<tr>
					<td>Nom du client</td>
					<td><input type="text" class="form-control" id="nom_cli"></td>
				</tr>
				
				<tr>
					<td>Date de Numérisation</td>
					<td><input type="text" class="form-control" id="dt_num"></td>
				</tr>
			</table>
      </div>
      <div class="modal-footer">
       
        <button type="button" class="btn btn-primary" id="btn_ajouter">Ajouter</button>
		 <button type="button" class="btn btn-default" data-dismiss="modal" id="annul_ajout">Annuler</button>
      </div>
    </div>
  </div>

