<script>
	$(document).ready(function(){
			$("#dt_num_mod").datepicker({
				dateFormat:"dd-mm-yy"
			});
			var num_cli = $("#id_cli_mod").val();
			var nom_cli = $("#nom_cli_mod").val();
			var dt_num = $("#dt_num_mod").val();
			$("#btn_modifier").click(function(){
				alert(num_cli+'aaa'+nom_cli+'--'+dt_num);
				
			})
	})
</script>

<table class="table table-striped">
	<tr>
		<td>Identifiant du client</td>
		<td><input type="text" class="form-control" id="id_cli_mod" value="<?php echo $res_aff['numero_client'] ?>"></td>
	</tr>
	<tr>
		<td>Nom du client</td>
		<td><input type="text" class="form-control" id="nom_cli_mod" value="<?php echo $res_aff['nom_client'] ?>"></td>
	</tr>
	<tr>
		<td>Date de Numérisation</td>
		<td><input type="text" class="form-control" id="dt_num_mod" value="<?php  
		$uu 	  = new DateTime($res_aff['date_numerisation']);
		$date_numerisation = date_format($uu,'d-m-Y');
		echo $date_numerisation; ?>"></td>
	</tr>
</table>
<div class="modal-footer">
		<button type="button" class="btn btn-primary" id="btn_modifier">Modifier </button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
        
      </div>