<?php
   $title = 'Accueil appli';
   $this->headTitle(utf8_encode($title));
?>
<ul class="breadcrumb">
   Mon application > index
</ul>

<a href="http://localhost/gestionco/public/monappli/ajouter"class="btn btn-primary  btn-lg"  data-toggle='modal' data-target='#modal_ad'> Ajouter </a>
<br/>
<br/>

<table id="my_data" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Identifiant du client</th>
                <th>Nom du client</th>
                <th>Date de numérisation</th>
                <th>Action</th>
               
            </tr>
        </thead>
       
       
 </table>
 
 <!-- Modal -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<div class="modal fade" id="modal_ad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>
