<?php
$request = $this->getHelperPluginManager()->getServiceLocator()->get('request');
$router = $this->getHelperPluginManager()->getServiceLocator()->get('router');
$matches = $router->match($request);
if(is_null($matches)){ 
    $route_name = 'home';
    $params = array('lang'=>'fr');
} else {    
    $route_name = $matches->getMatchedRouteName();
    $params = $matches->getParams();
}

if(isset($params['lang'])) $lang = $params['lang'];
else $lang =  'fr';
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $lang; ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('test '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home',array('lang'=>$lang)) ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home',array('lang'=>$lang)) ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->  
                 
                
                 
                 
            </div>
        </nav>
        <div class="container">
            <div class="languages">
                <label><?php echo $this->translate('Your language'); ?> :</label>
                <ul>
                    <li>
                        <a href="<?php $params['lang'] = 'fr'; echo $this->url($route_name,$params) ?>"><span class="flag flag-fr"><?php echo $this->translate('French') ?></span></a>
                        <a href="<?php $params['lang'] = 'nl'; echo $this->url($route_name,$params) ?>"><span class="flag flag-nl"><?php echo $this->translate('Dutch') ?></span></a>
                        <a href="<?php $params['lang'] = 'en'; echo $this->url($route_name,$params) ?>"><span class="flag flag-en"><?php echo $this->translate('English') ?></span></a>
                        <a href="<?php $params['lang'] = 'ru'; echo $this->url($route_name,$params) ?>"><span class="flag flag-ru"><?php echo $this->translate('Russian') ?></span></a>
                    </li>
                </ul>
            </div>
            <?php //var_dump($this->getHelperPluginManager()->getServiceLocator()->get('router')->match($this->getHelperPluginManager()->getServiceLocator()->get('request'))); ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
